
import { Montserrat } from "next/font/google";
import "./globals.css";

import Menu from "@/components/menu/Menu.js";

const montserrat = Montserrat({ subsets: ["latin"] });

export const metadata = {
  title: "iMOVS | Tecnología digital",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={montserrat.className}>
      <Menu />
      <body >{children}</body>
    </html>
  );
}
